/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@class CKAggregateConversation, CKMessage, CKMessageComposition, CKService, IMChat, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface CKConversation : NSObject
{
    CKAggregateConversation *_aggregateConversation;
    NSMutableArray *_messages;
    NSString *_name;
    int _unreadCount;
    NSMutableArray *_failedMessages;
    NSMutableArray *_pendingMessages;
    CKMessage *_latestIncomingMessage;
    BOOL _hasPlaceholder;
    CKMessage *_placeholderMessage;
    CKMessage *_outgoingTypingMessage;
    CKMessage *_incomingTypingMessage;
    NSArray *_names;
    NSArray *_recipients;
    unsigned int _recipientHash;
    NSMutableDictionary *_groupMessages;
    NSMutableArray *_queuedGroupMessages;
    int _groupAddStack;
    BOOL _moreMessagesToLoad;
    int _limitToLoad;
    CKService *_service;
    BOOL _updatesDisabled;
    BOOL _needsPostAfterUpdate;
    BOOL _wantsAnimatedPost;
    NSString *_groupID;
    IMChat *_imChat;
}

@property(retain, nonatomic) CKMessageComposition *unsentComposition;
- (id)initWithGroupID:(id)arg1 service:(id)arg2;
- (id)recipient;
- (unsigned int)recipientsHash;
- (void)requestRecipientStatuses;
- (void)dealloc;
- (void)setName:(id)arg1;
- (id)name;
- (id)latestMessage;
- (id)date;
- (void)setRecipients:(id)arg1;
- (id)recipients;
- (void)updateRecipients:(id)arg1;
- (void)_recalculateUnreadCounts;
- (void)removeMessage:(id)arg1 postUpdate:(BOOL)arg2;
- (void)removeMessage:(id)arg1;
- (BOOL)isEmpty;
- (BOOL)isPlaceholder;
- (void)addPlaceholderMessageWithDate:(id)arg1;
- (id)placeholderMessage;
- (void)_setPlaceholderMessage:(id)arg1;
- (void)_refreshMoreToLoadFlag;
- (void)_postChangeUpdate:(BOOL)arg1;
@property(nonatomic) BOOL updatesDisabled;
- (void)postChangedUpdate:(BOOL)arg1;
- (void)updateMessage:(id)arg1;
- (int)addMessage:(id)arg1 incrementUnreadCount:(BOOL)arg2;
- (void)beginGroupAdd;
- (void)_addGroupMessage:(id)arg1;
- (int)endGroupAddIncrementingUnreadCount:(BOOL)arg1;
- (void)resetPendingMessages;
- (void)markAllMessagesAsRead;
- (void)removeAllMessages;
- (void)_deleteAllMessagesAndRemoveGroup:(BOOL)arg1;
- (void)deleteAllMessages;
- (void)deleteAllMessagesAndRemoveGroup;
- (BOOL)moreMessagesToLoad;
- (void)setMoreMessagesToLoad:(BOOL)arg1;
- (void)setLoadedMessages:(id)arg1;
- (void)_reloadMessagesToLimit;
- (void)loadLastMessage;
- (void)loadAllMessages;
- (void)loadMoreMessages;
@property(nonatomic) int limitToLoad; // @synthesize limitToLoad=_limitToLoad;
- (id)pendingMessages;
- (id)messages;
- (id)latestIncomingMessage;
- (void)resetUnreadCount;
- (void)setUnreadCount:(int)arg1;
- (int)unreadCount;
- (BOOL)hasUnreadMessages;
- (id)_trulyLatestMessage;
- (int)compareByDateDescending:(id)arg1;
- (void *)abRecord;
- (int)propertyType;
- (int)identifier;
- (id)uniqueIdentifier;
- (void)resetCaches;
- (id)groupMessageWithAssociationID:(int)arg1;
- (void)pendingMessagesTotalMessages:(int *)arg1 percentComplete:(float *)arg2;
- (BOOL)containsConversation:(id)arg1;
- (id)description;
@property(readonly, nonatomic) IMChat *imChat;
@property(readonly, nonatomic) NSArray *groupIDs;
@property(retain, nonatomic) CKMessage *incomingTypingMessage; // @synthesize incomingTypingMessage=_incomingTypingMessage;
@property(retain, nonatomic) CKMessage *outgoingTypingMessage; // @synthesize outgoingTypingMessage=_outgoingTypingMessage;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(readonly, nonatomic) NSMutableArray *failedMessages; // @synthesize failedMessages=_failedMessages;
@property(readonly, nonatomic) CKService *service; // @synthesize service=_service;
@property(nonatomic) CKAggregateConversation *aggregateConversation; // @synthesize aggregateConversation=_aggregateConversation;

@end

