/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "CKService.h"

@interface CKSMSService : CKService
{
    int _lastMessageRowID;
}

+ (id)sharedSMSService;
+ (id)dbPath;
+ (void)migrate;
+ (BOOL)willSendMMSByDefaultForConversation:(id)arg1;
- (BOOL)isAvailable;
- (Class)entityClass;
- (id)userFormattedAlphanumericStringForAddress:(id)arg1;
- (int)failedSendCount;
- (BOOL)hasActiveConversations;
- (id)copyLatestIncomingMessagesFromRowID:(unsigned int)arg1 offset:(unsigned int)arg2 limit:(unsigned int)arg3;
- (int)unreadCountForConversation:(id)arg1;
- (BOOL)dbFull;
- (void)markAllMessagesInConversationAsRead:(id)arg1;
- (id)_newCKSMSMessage:(id)arg1;
- (void)_receivedMessage:(id)arg1 replace:(BOOL)arg2 postInternalNotification:(BOOL)arg3;
- (void)_receivedDeliveryReceiptForMessage:(id)arg1;
- (void)_sentMessage:(id)arg1 postInternalNotification:(BOOL)arg2;
- (void)_sendError:(id)arg1;
- (void)_databaseFull:(id)arg1;
- (id)createConversationWithRecipients:(id)arg1;
- (id)conversationIDWithRecipients:(id)arg1;
- (void)_registerForCTNotifications;
- (id)init;
- (void)dealloc;
- (id)abPropertyTypes;
- (id)_newMMSMessageWithParts:(id)arg1 forConversation:(id)arg2 subject:(id)arg3;
- (id)_newMMSMessageWithComposition:(id)arg1 forConversation:(id)arg2;
- (id)_newSMSMessageWithText:(id)arg1 forConversation:(id)arg2;
- (id)newMessageWithMessage:(id)arg1 forConversation:(id)arg2 isForward:(BOOL)arg3;
- (BOOL)isSMSDeliverableComposition:(id)arg1 forConversationWithRecipientCount:(unsigned int)arg2 recipientsRequired:(BOOL)arg3;
- (id)newMessageWithComposition:(id)arg1 forConversation:(id)arg2;
- (BOOL)containsConversation:(id)arg1;
- (int)unreadConversationCount;
- (int)unreadCount;
- (id)placeholderMessageForConversation:(id)arg1 withDate:(id)arg2;
- (void)sendMessage:(id)arg1;
- (void)fixupNames;
- (id)lookupRecipientsForConversation:(id)arg1;
- (void)updateRecipients:(id)arg1 forConversation:(id)arg2;
- (id)conversationSummaries:(id)arg1 groupIDs:(id)arg2;
- (void)messagesForConversation:(id)arg1;
- (void)deleteMessagesForConversationIDs:(id)arg1 removeConversations:(BOOL)arg2;
- (id)copyEntityForAddressString:(id)arg1;
- (id)unknownEntity;
- (id)headerTitleForEntities:(id)arg1;
- (id)headerTitleForComposeRecipients:(id)arg1 mediaObjects:(id)arg2 subject:(id)arg3;
- (BOOL)restrictsMediaObjects;
- (BOOL)supportsMediaAttachments;
- (BOOL)supportsCharacterCountForConversation:(id)arg1;
- (BOOL)canSendMessageWithMediaObjectTypes:(int *)arg1;
- (BOOL)canAcceptMediaObjectType:(int)arg1 givenMediaObjects:(id)arg2;
- (BOOL)canSendToRecipients:(id)arg1 withAttachments:(id)arg2 alertIfUnable:(BOOL)arg3;
- (int)maxRecipientCount;
- (BOOL)canAcceptMediaObject:(id)arg1 givenMediaObjects:(id)arg2;
- (int)maxAttachmentCount;
- (BOOL)isValidAddress:(id)arg1;
- (double)maxTrimDurationForMediaType:(int)arg1;
- (void)prepareForResume;
- (void)prepareForSuspend;
- (id)displayName;
- (int)buttonColor;

@end