/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "CKMessage.h"

@class CKSMSMessageDelivery, NSArray, NSMutableArray, NSString;

@interface CKSMSMessage : CKMessage
{
    NSMutableArray *_messages;
    int _associationID;
    int _rowID;
    CKSMSMessageDelivery *_delivery;
    unsigned int _messagePartsLoaded:1;
    unsigned int _isFromDowngrading:1;
    unsigned int _subjectLoaded:1;
    NSArray *_messageParts;
    NSString *_subject;
}

@property(retain, nonatomic) CKSMSMessageDelivery *delivery; // @synthesize delivery=_delivery;
- (void)dealloc;
- (void)_loadFailedSendCount;
- (BOOL)isDelivered;
- (BOOL)isPlaceholder;
- (BOOL)isFromDowngrading;
- (void)setIsFromDowngrading:(BOOL)arg1;
- (BOOL)isFromMe;
- (BOOL)isRead;
- (int)totalMessageCount;
- (int)sentCount;
- (void)_storeUIFlags:(unsigned long)arg1;
- (void)_loadUIFlags;
- (void)_loadSubject;
- (id)subject;
- (void)_loadText;
- (BOOL)_loadOutgoing;
- (id)_newParts;
- (void)addMessage:(void *)arg1;
- (void)setMessages:(id)arg1;
- (void)markAsRead;
- (double)_loadDate;
- (void)permanentlyRemoveMessage;
- (id)messages;
- (unsigned int)messagePartCount;
- (id)messagePartAtIndex:(unsigned int)arg1;
- (id)messagePartWithRowID:(int)arg1;
- (void)_setParts:(id)arg1;
- (void)loadParts;
- (id)initWithCTMessage:(void *)arg1 messageParts:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithCTMessages:(id)arg1 messageParts:(id)arg2;
- (id)initWithRowID:(int)arg1;
- (int)messageCount;
- (BOOL)isForward;
- (void)prepareToResend;
- (id)sender;
- (id)address;
- (BOOL)containsDisplayableMessageParts;
- (void)deleteMessagePart:(id)arg1;
- (void)_setupDeliveryIfPending;
- (void)deliveredSubpart:(int)arg1 totalSubparts:(int)arg2 success:(BOOL)arg3;
- (void)deliveryCompletedForMessage:(id)arg1;
- (void)deliveryFailedForMessage:(id)arg1;
- (void)deliveryPartiallyFailedForMessage:(id)arg1;
- (id)guid;
- (id)sequenceNumber;
@property(readonly, nonatomic) int rowID; // @synthesize rowID=_rowID;
@property(readonly, nonatomic) int associationID; // @synthesize associationID=_associationID;

@end

